### PR TITLE
Add zh-CN locale

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by Infocatcher** [comment]
Thanks!

**Comment by Infocatcher** [comment]
Also please translate extension description in <a href="https://github.com/Infocatcher/Link_Properties_Plus/blob/master/install.rdf">install.rdf</a>:
```xml
	<em:localized>
		<Description>
			<em:locale>en-US</em:locale>
			<em:name>Link Properties Plus</em:name>
			<em:description>Provides extended link properties: size of linked file, last modified time, etc.</em:description>
			<em:creator>Infocatcher</em:creator>
			<em:developer>Torisugari (author of the original Extended Link Properties extension)</em:developer>
			<em:contributor>Jane Ocean (Seamaiden)</em:contributor>
			<em:contributor>Icons: Farm-fresh (http://fatcow.com/free-icons) and Gnome (https://gnome.org/)</em:contributor>
		</Description>
	</em:localized>
```

**Comment by yfdyh000** [comment]
@Infocatcher This translation already exists in extensions.linkPropertiesPlus@infocatcher.description, and I've see the localized description even without this metadata.

**Comment by Infocatcher** [comment]
Oh, yes, but this is legacy method. And not used for disabled extension.
And there is some additional strings for about window (Add-on Manager -> extension -> about).

**Pull request merged**
